Add credential provider support
alisaifee/coredis pull request #253
Opened 2024-12-02 19:31 UTC by trentbitterman

Adds an abstract credential provider class that can be used to programmatically supply credentials at
authentication time, instead of just a static username and password.

2024-12-02 19:33 UTC, trentbitterman commented
Closes #246

2024-12-02 21:52 UTC, trentbitterman commented on coredis/credentials.py
> +    def get_credentials(self) -> PassOnly | UserPass:
I thought about making this method async, but wasn't sure what would be best. Do you have any preferences?

2024-12-03 18:02 UTC, alisaifee requested changes
Generally this looks great! Thank you for the comprehensive and very clean contribution!

I've left a few minor suggestions for your consideration. Additionally if you have an implementation for an IAM provider for example - perhaps this could be added to `coredis.recipes` and referenced in the documentation?

2024-12-03 18:02 UTC, alisaifee commented on coredis/client/basic.py
> +        :param credential_provider: CredentialProvider to get authentication creds
```suggestion
        :param credential_provider: CredentialProvider to get authentication credentials
```

2024-12-03 18:02 UTC, alisaifee commented on coredis/connection.py
> +        if creds:
Minor tweak if you like (the codebase generally needs a bit of modernization)
```suggestion
        if creds := (
            self.credential_provider.get_credentials()
            if self.credential_provider
            else (
                UserPassCredentialProvider(self.username, self.password)
                if (self.username or self.password)
                else None
            )
        ):
```

2024-12-03 18:02 UTC, alisaifee commented on coredis/credentials.py
> +    def get_credentials(self) -> PassOnly | UserPass:
Unfortunately I don't know enough about the different credentials providers that are in use with redis in the wild. If at all there is a possibility that an io request needs to be made to generate the credentials then this method should be async (and perhaps there is no harm defaulting to that since it will always be used in an async context)

2024-12-03 18:02 UTC, alisaifee commented on coredis/credentials.py
> +        )
Would it be possible to skip `PassOnly` and hardcode the `default` value here? This would then simplify the handling in the connection class as well.
```suggestion
    def get_credentials(self) -> UserPass:
        return UserPass(self.username or "default", self.password)
```

2024-12-03 18:41 UTC, trentbitterman commented on coredis/credentials.py
> +        )
I like that, although I think we would need to modify the return type of the abstract method too if we were going to simplify the code in the connection class. Did you want that changed as well?

2024-12-03 19:58 UTC, alisaifee commented on coredis/credentials.py
> +        )
Ah yes, missed that tweak!

2024-12-03 22:23 UTC, trentbitterman commented
@alisaifee Thanks for the review! Let me know if there are any other changes you'd like me to make.

2024-12-03 22:32 UTC, alisaifee commented
> @alisaifee Thanks for the review! Let me know if there are any other changes you'd like me to make.

Wow, amazing turnaround to address the suggestion! Thank you! Looks great to me. I wasn't able to verify the rendering of the docs since I've broken my local sphinx environment but that's a minor detail we can iron out in master.

Regarding the typing issues in CI with respect to boto - feel free to add it to the ignore list.

2024-12-03 22:40 UTC, trentbitterman commented
@alisaifee Hopefully that's the correct place to ignore them. Let me know if it's not.

2024-12-03 22:51 UTC, alisaifee commented on pyproject.toml
> +    "botocore",
```suggestion
    "botocore.*",
```

2024-12-03 22:52 UTC, alisaifee commented on coredis/recipes/credentials/iam_provider.py
> +    @cached(cache=TTLCache(maxsize=128, ttl=900))
```suggestion
    @cached(cache=TTLCache(maxsize=128, ttl=900)). # type: ignore[misc]
```

2024-12-03 22:53 UTC, alisaifee commented
> @alisaifee Hopefully that's the correct place to ignore them. Let me know if it's not.

It is indeed. Needed a few tweaks to get past mypy. Since it's a recipe it's fine to be a bit relaxed on the type strictness IMO.

2024-12-03 23:32 UTC, alisaifee approved these changes

2024-12-04 00:27 UTC, alisaifee commented
@trentbitterman unless you have anything else to add, I'll probably merge this once CI is done.

2024-12-04 02:00 UTC, trentbitterman commented
That works for me, I didn’t have any other changes planned. Thanks!

2024-12-04 02:41 UTC, merged